# ==============================================================
# = PriceArt Web Service - Versione Autenticazione JWT
# ==============================================================
server:
  port: 5071

spring:
  profiles:
    active: list1
  cloud:
    config:
      uri: http://localhost:8888
      profile: list100
      #label: list3
      enabled: false
  # ==============================================================
  # = Proprietà Fonte Dati PostgreSQL
  # ==============================================================
  datasource:
    initialization-mode: always
    password: 123_Stella
    platform: postgres
    url: jdbc:postgresql://localhost:5433/AlphaShop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
# ==============================================================
# = Proprietà Servizio gestUser
# ==============================================================
gestuser:
  password: BimBumBam_2018
  srvUrl: http://localhost:8019/api/utenti/cerca/userid/
  userId: ReadUser

# ==============================================================
# = Parametri Sicurezza JWT
# ==============================================================
sicurezza:
  uri: /auth
  refresh: /refresh
  header: Authorization
  prefix: Bearer
  expiration: 86400
  secret: 123_Stella
